name: mon_heure
description: An elegant cross-platform personal punch-in/punch-out tracker.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.21.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^1.0.0
  pdf: ^3.10.7
  printing: ^5.11.1
  intl: ^0.20.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 